### ISSUE TITLE
Build error : Not in scope: data constructor `ResponseBuilder'

### ISSUE THREAD

**Issue by imp1377** [ndmitchell/hoogle#40]
src/General/Web.hs:44:19:
    Not in scope: data constructor `ResponseBuilder'

Cannot build with wai-2.0.0
